# Generated by Django 4.2.1 on 2023-05-29 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=256, verbose_name='اسم الضابط')),
                ('rank', models.CharField(blank=True, choices=[('جندي', 'جندي'), ('عريف', 'عريف'), ('رقيب', 'رقيب'), ('رقيب اول', 'رقيب اول'), ('مساعد', 'مساعد'), ('مساعد اول', 'مساعد اول'), ('ملازم', 'ملازم'), ('ملازم اول', 'ملازم اول'), ('نقيب', 'نقيب'), ('رائد', 'رائد'), ('مقدم', 'مقدم'), ('عقيد', 'عقيد'), ('عميد', 'عميد')], max_length=64, null=True)),
                ('role', models.CharField(choices=[('1', 'رئيس الفرع'), ('2', 'ضابط')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
