# Generated by Django 4.2.1 on 2023-05-29 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('task_attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('state', models.CharField(choices=[('جاري التنفيذ', 'جاري التنفيذ'), ('بإنتظار تأكيد الإنهاء', 'بإنتظار تأكيد الإنهاء'), ('تم إنجازه', 'تم إنجازه')], default='جاري التنفيذ', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('officers', models.ManyToManyField(related_name='tasks', to='accounts.officer')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to='accounts.officer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.task')),
            ],
        ),
    ]
